AnimalData = {
	["Svinina Bombardino"] = {DisplayName = "Svinina Bombardino", Rarity = "Common"},
	["Pipi Corni"] = {DisplayName = "Pipi Corni", Rarity = "Common"},
	["Lirilì Larilà"] = {DisplayName = "Lirilì Larilà", Rarity = "Common"},
	["Pipi Kiwi"] = {DisplayName = "Pipi Kiwi", Rarity = "Common"},
	["Raccooni Jandelini"] = {DisplayName = "Raccooni Jandelini", Rarity = "Common"},
	["Noobini Pizzanini"] = {DisplayName = "Noobini Pizzanini", Rarity = "Common"},
	["Fluriflura"] = {DisplayName = "Fluriflura", Rarity = "Common"},
	["Tim Cheese"] = {DisplayName = "Tim Cheese", Rarity = "Common"},
	["Talpa Di Fero"] = {DisplayName = "Talpa Di Fero", Rarity = "Common"},
	["Ta Ta Ta Ta Sahur"] = {DisplayName = "Ta Ta Ta Ta Sahur", Rarity = "Rare"},
	["Gangster Footera"] = {DisplayName = "Gangster Footera", Rarity = "Rare"},
	["Trippi Troppi"] = {DisplayName = "Trippi Troppi", Rarity = "Rare"},
	["Cacto Hipopotamo"] = {DisplayName = "Cacto Hipopotamo", Rarity = "Rare"},
	["Bandito Bobritto"] = {DisplayName = "Bandito Bobritto", Rarity = "Rare"},
	["Tric Trac Baraboom"] = {DisplayName = "Tric Trac Baraboom", Rarity = "Rare"},
	["Pipi Avocado"] = {DisplayName = "Pipi Avocado", Rarity = "Rare"},
	["Tung Tung Tung Sahur"] = {DisplayName = "Tung Tung Tung Sahur", Rarity = "Rare"},
	["Boneca Ambalabu"] = {DisplayName = "Boneca Ambalabu", Rarity = "Rare"},
	["Bambini Crostini"] = {DisplayName = "Bambini Crostini", Rarity = "Epic"},
	["Penguino Cocosino"] = {DisplayName = "Penguino Cocosino", Rarity = "Epic"},
	["Brr Brr Patapim"] = {DisplayName = "Brr Brr Patapim", Rarity = "Epic"},
	["Avocadini Antilopini"] = {DisplayName = "Avocadini Antilopini", Rarity = "Epic"},
	["Trulimero Trulicina"] = {DisplayName = "Trulimero Trulicina", Rarity = "Epic"},
	["Salamino Penguino"] = {DisplayName = "Salamino Penguino", Rarity = "Epic"},
	["Bananita Dolphinita"] = {DisplayName = "Bananita Dolphinita", Rarity = "Epic"},
	["Ti Ti Ti Sahur"] = {DisplayName = "Ti Ti Ti Sahur", Rarity = "Epic"},
	["Brri Brri Bicus Dicus Bombicus"] = {DisplayName = "Brri Brri Bicus Dicus Bombicus", Rarity = "Epic"},
	["Cappuccino Assassino"] = {DisplayName = "Cappuccino Assassino", Rarity = "Epic"},
	["Perochello Lemonchello"] = {DisplayName = "Perochello Lemonchello", Rarity = "Epic"},
	["Avocadini Guffo"] = {DisplayName = "Avocadini Guffo", Rarity = "Epic"},
	["Cocosini Mama"] = {DisplayName = "Cocosini Mama", Rarity = "Legendary"},
	["Pandaccini Bananini"] = {DisplayName = "Pandaccini Bananini", Rarity = "Legendary"},
	["Chimpanzini Bananini"] = {DisplayName = "Chimpanzini Bananini", Rarity = "Legendary"},
	["Glorbo Fruttodrillo"] = {DisplayName = "Glorbo Fruttodrillo", Rarity = "Legendary"},
	["Strawberrelli Flamingelli"] = {DisplayName = "Strawberrelli Flamingelli", Rarity = "Legendary"},
	["Chef Crabracadabra"] = {DisplayName = "Chef Crabracadabra", Rarity = "Legendary"},
	["Pi Pi Watermelon"] = {DisplayName = "Pi Pi Watermelon", Rarity = "Legendary"},
	["Ballerina Cappuccina"] = {DisplayName = "Ballerina Cappuccina", Rarity = "Legendary"},
	["Sigma Boy"] = {DisplayName = "Sigma Boy", Rarity = "Legendary"},
	["Blueberrinni Octopusini"] = {DisplayName = "Blueberrinni Octopusini", Rarity = "Legendary"},
	["Quivioli Ameleonni"] = {DisplayName = "Quivioli Ameleonni", Rarity = "Legendary"},
	["Burbaloni Loliloli"] = {DisplayName = "Burbaloni Loliloli", Rarity = "Legendary"},
	["Lionel Cactuseli"] = {DisplayName = "Lionel Cactuseli", Rarity = "Legendary"},
	["Pipi Potato"] = {DisplayName = "Pipi Potato", Rarity = "Legendary"},
	["Tigrilini Watermelini"] = {DisplayName = "Tigrilini Watermelini", Rarity = "Mythic"},
	["Spioniro Golubiro"] = {DisplayName = "Spioniro Golubiro", Rarity = "Mythic"},
	["Bombombini Gusini"] = {DisplayName = "Bombombini Gusini", Rarity = "Mythic"},
	["Tracoducotulu Delapeladustuz"] = {DisplayName = "Tracoducotulu Delapeladustuz", Rarity = "Mythic"},
	["Cavallo Virtuoso"] = {DisplayName = "Cavallo Virtuoso", Rarity = "Mythic"},
	["Tob Tobi Tobi"] = {DisplayName = "Tob Tobi Tobi", Rarity = "Mythic"},
	["Carloo"] = {DisplayName = "Carloo", Rarity = "Mythic"},
	["Rhino Toasterino"] = {DisplayName = "Rhino Toasterino", Rarity = "Mythic"},
	["Te Te Te Sahur"] = {DisplayName = "Te Te Te Sahur", Rarity = "Mythic"},
	["Orangutini Ananassini"] = {DisplayName = "Orangutini Ananassini", Rarity = "Mythic"},
	["Carrotini Brainini"] = {DisplayName = "Carrotini Brainini", Rarity = "Mythic"},
	["Lerulerulerule"] = {DisplayName = "Lerulerulerule", Rarity = "Mythic"},
	["Frigo Camelo"] = {DisplayName = "Frigo Camelo", Rarity = "Mythic"},
	["Gorillo Watermelondrillo"] = {DisplayName = "Gorillo Watermelondrillo", Rarity = "Mythic"},
	["Bombardiro Crocodilo"] = {DisplayName = "Bombardiro Crocodilo", Rarity = "Mythic"},
	["Zibra Zubra Zibralini"] = {DisplayName = "Zibra Zubra Zibralini", Rarity = "Mythic"},
	["Ganganzelli Trulala"] = {DisplayName = "Ganganzelli Trulala", Rarity = "Mythic"},
	["Avocadorilla"] = {DisplayName = "Avocadorilla", Rarity = "Mythic"},
	["Bulbito Bandito Traktorito"] = {DisplayName = "Bulbito Bandito Traktorito", Rarity = "Brainrot God"},
	["Urubini Flamenguini"] = {DisplayName = "Urubini Flamenguini", Rarity = "Brainrot God"},
	["Crabbo Limonetta"] = {DisplayName = "Crabbo Limonetta", Rarity = "Brainrot God"},
	["Tukanno Bananno"] = {DisplayName = "Tukanno Bananno", Rarity = "Brainrot God"},
	["Tigroligre Frutonni"] = {DisplayName = "Tigroligre Frutonni", Rarity = "Brainrot God"},
	["Odin Din Din Dun"] = {DisplayName = "Odin Din Din Dun", Rarity = "Brainrot God"},
	["Gattatino Nyanino"] = {DisplayName = "Gattatino Nyanino", Rarity = "Brainrot God"},
	["Mastodontico Telepiedone"] = {DisplayName = "Mastodontico Telepiedone", Rarity = "Brainrot God"},
	["Alessio"] = {DisplayName = "Alessio", Rarity = "Brainrot God"},
	["Los Orcalitos"] = {DisplayName = "Los Orcalitos", Rarity = "Brainrot God"},
	["Unclito Samito"] = {DisplayName = "Unclito Samito", Rarity = "Brainrot God"},
	["Trippi Troppi Troppa Trippa"] = {DisplayName = "Trippi Troppi Troppa Trippa", Rarity = "Brainrot God"},
	["Brr es Teh Patipum"] = {DisplayName = "Brr es Teh Patipum", Rarity = "Brainrot God"},
	["Los Tungtungtungcitos"] = {DisplayName = "Los Tungtungtungcitos", Rarity = "Brainrot God"},
	["Cacasito Satalito"] = {DisplayName = "Cacasito Satalito", Rarity = "Brainrot God"},
	["Los Bombinitos"] = {DisplayName = "Los Bombinitos", Rarity = "Brainrot God"},
	["Tralalero Tralala"] = {DisplayName = "Tralalero Tralala", Rarity = "Brainrot God"},
	["Orcalero Orcala"] = {DisplayName = "Orcalero Orcala", Rarity = "Brainrot God"},
	["Los Crocodillitos"] = {DisplayName = "Los Crocodillitos", Rarity = "Brainrot God"},
	["Tralalita Tralala"] = {DisplayName = "Tralalita Tralala", Rarity = "Brainrot God"},
	["Cocofanto Elefanto"] = {DisplayName = "Cocofanto Elefanto", Rarity = "Brainrot God"},
	["Piccione Macchina"] = {DisplayName = "Piccione Macchina", Rarity = "Brainrot God"},
	["Matteo"] = {DisplayName = "Matteo", Rarity = "Brainrot God"},
	["Ballerino Lololo"] = {DisplayName = "Ballerino Lololo", Rarity = "Brainrot God"},
	["Tartaruga Cisterna"] = {DisplayName = "Tartaruga Cisterna", Rarity = "Brainrot God"},
	["Tipi Topi Taco"] = {DisplayName = "Tipi Topi Taco", Rarity = "Brainrot God"},
	["Bombardini Tortinii"] = {DisplayName = "Bombardini Tortinii", Rarity = "Brainrot God"},
	["Girafa Celestre"] = {DisplayName = "Girafa Celestre", Rarity = "Brainrot God"},
	["Agarrini la Palini"] = {DisplayName = "Agarrini la Palini", Rarity = "Secret"},
	["Espresso Signora"] = {DisplayName = "Espresso Signora", Rarity = "Brainrot God"},
	["Trenostruzzo Turbo 3000"] = {DisplayName = "Trenostruzzo Turbo 3000", Rarity = "Brainrot God"},
	["Pakrahmatmamat"] = {DisplayName = "Pakrahmatmamat", Rarity = "Brainrot God"},
	["Los Spyderinis"] = {DisplayName = "Los Spyderinis", Rarity = "Secret"},
	["Dul Dul Dul"] = {DisplayName = "Dul Dul Dul", Rarity = "Secret"},
	["Nuclearo Dinossauro"] = {DisplayName = "Nuclearo Dinossauro", Rarity = "Secret"},
	["Nooo My Hotspot"] = {DisplayName = "Nooo My Hotspot", Rarity = "Secret"},
	["Pot Hotspot"] = {DisplayName = "Pot Hotspot", Rarity = "Secret"},
	["Los Matteos"] = {DisplayName = "Los Matteos", Rarity = "Secret"},
	["Los Hotspotsitos"] = {DisplayName = "Los Hotspotsitos", Rarity = "Secret"},
	["Spaghetti Tualetti"] = {DisplayName = "Spaghetti Tualetti", Rarity = "Secret"},
	["La Vacca Saturno Saturnita"] = {DisplayName = "La Vacca Saturno Saturnita", Rarity = "Secret"},
	["Guerriro Digitale"] = {DisplayName = "Guerriro Digitale", Rarity = "Secret"},
	["Bisonte Giuppitere"] = {DisplayName = "Bisonte Giuppitere", Rarity = "Secret"},
	["Blackhole Goat"] = {DisplayName = "Blackhole Goat", Rarity = "Secret"},
	["Karkerkar Kurkur"] = {DisplayName = "Karkerkar Kurkur", Rarity = "Secret"},
	["Garama and Madundung"] = {DisplayName = "Garama and Madundung", Rarity = "Secret"},
	["Chicleteira Bicicleteira"] = {DisplayName = "Chicleteira Bicicleteira", Rarity = "Secret"},
	["Ketupat Kepat"] = {DisplayName = "Ketupat Kepat", Rarity = "Secret"},
	["Job Job Job Sahur"] = {DisplayName = "Job Job Job Sahur", Rarity = "Secret"},
	["Torrtuginni Dragonfrutini"] = {DisplayName = "Torrtuginni Dragonfrutini", Rarity = "Secret"},
	["Esok Sekolah"] = {DisplayName = "Esok Sekolah", Rarity = "Secret"},
	["Ketchuru and Musturu"] = {DisplayName = "Ketchuru and Musturu", Rarity = "Secret"},
	["La Supreme Combinasion"] = {DisplayName = "La Supreme Combinasion", Rarity = "Secret"},
	["Los Tralaleritos"] = {DisplayName = "Los Tralaleritos", Rarity = "Secret"},
	["Sammyni Spyderini"] = {DisplayName = "Sammyni Spyderini", Rarity = "Secret"},
	["Las Vaquitas Saturnitas"] = {DisplayName = "Las Vaquitas Saturnitas", Rarity = "Secret"},
	["La Grande Combinasion"] = {DisplayName = "La Grande Combinasion", Rarity = "Secret"},
	["Dragon Cannelloni"] = {DisplayName = "Dragon Cannelloni", Rarity = "Secret"},
	["Graipuss Medussi"] = {DisplayName = "Graipuss Medussi", Rarity = "Secret"},
	["Las Tralaleritas"] = {DisplayName = "Las Tralaleritas", Rarity = "Secret"},
	["Los Combinasionas"] = {DisplayName = "Los Combinasionas", Rarity = "Secret"},
	["Strawberry Elephant"] = {DisplayName = "Strawberry Elephant", Rarity = "OG"},
}
